//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_DeliveryNow
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DeliveryNowDBEntities : DbContext
    {
        public DeliveryNowDBEntities()
            : base("name=DeliveryNowDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Reports> Reports { get; set; }
    
        public virtual int Insert_Customers_sp(string customer_username, string customer_name, string customer_lastname, string customer_password, string customer_ph_number, string customer_address, string customer_pay_method)
        {
            var customer_usernameParameter = customer_username != null ?
                new ObjectParameter("customer_username", customer_username) :
                new ObjectParameter("customer_username", typeof(string));
    
            var customer_nameParameter = customer_name != null ?
                new ObjectParameter("customer_name", customer_name) :
                new ObjectParameter("customer_name", typeof(string));
    
            var customer_lastnameParameter = customer_lastname != null ?
                new ObjectParameter("customer_lastname", customer_lastname) :
                new ObjectParameter("customer_lastname", typeof(string));
    
            var customer_passwordParameter = customer_password != null ?
                new ObjectParameter("customer_password", customer_password) :
                new ObjectParameter("customer_password", typeof(string));
    
            var customer_ph_numberParameter = customer_ph_number != null ?
                new ObjectParameter("customer_ph_number", customer_ph_number) :
                new ObjectParameter("customer_ph_number", typeof(string));
    
            var customer_addressParameter = customer_address != null ?
                new ObjectParameter("customer_address", customer_address) :
                new ObjectParameter("customer_address", typeof(string));
    
            var customer_pay_methodParameter = customer_pay_method != null ?
                new ObjectParameter("customer_pay_method", customer_pay_method) :
                new ObjectParameter("customer_pay_method", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Customers_sp", customer_usernameParameter, customer_nameParameter, customer_lastnameParameter, customer_passwordParameter, customer_ph_numberParameter, customer_addressParameter, customer_pay_methodParameter);
        }
    }
}
