//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_DeliveryNow
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Details
    {
        public string order_id { get; set; }
        public string product_id { get; set; }
        public decimal product_units { get; set; }
        public decimal product_price { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
